<?php

namespace Panel;

use GrahamCampbell\DigitalOcean\DigitalOceanManager;
use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\DigitalOcean\Facades\DigitalOcean;
use Illuminate\Support\Facades\Auth;

class Domain extends Model
{
    protected $fillable = [
        'user_id',
        'name'
    ];

    public static function add($name,$ip)
    {
        try{
            DigitalOcean::domain()->create($name,$ip);
        }catch (\Exception $e){
            return redirect(route('dns.index'))->with('error',$e->getMessage());
        }
        $domain = Domain::create([
            'user_id' => 1,
            'name' => $name
        ]);
        return redirect(route('dns.index'))->with('status','Domain Added');
    }


    public function getRouteKeyName()
    {
        return 'name';
    }

    public function user(){
        return $this->belongsTo('Panel\User');
    }

    public function records(){
        return DigitalOcean::domainRecord()->getAll($this->name);
    }

    public function delete()
    {
        DigitalOcean::domain()->delete($this->name);
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
